### PR TITLE
modify export and update return type in camera-controls.d.ts

### PR DESCRIPTION
**Pull request by 1016482011**
Hi, friend, I find some small problems when I apply the awsome cameraControl into my ts project. 
 1. _camera-controls.d.ts_ use the different export with the _camera-controls.js_, which cause I can not import the `CameraControls` in typescript project. 

2.  the public method _update_ should return `boolean` instead of  `void`

### CODE REVIEW

**Comment by yomotsu** [comment]
Thanks again! 
Actually, this has been already resolved at another PR: 
https://github.com/yomotsu/camera-controls/pull/26/files#diff-c74ac60224ef1d1a89832447342274ed and it should work. Looks good?

**Comment by 1016482011** [comment]
Sure,It  works well, thanks

**Comment by FMS-Cat** [comment]
@1016482011 I'm so sorry about my bad, hope newer d.ts work fine :bow:

**Comment by 1016482011** [comment]
@FMS-Cat You are a nice man,  the  .d.ts help me much in ts project

**Pull request closed without merging**
