### PR TITLE
exposing angles

### PR DESCRIPTION
**Pull request by yomotsu**
see https://github.com/yomotsu/camera-controls/issues/93

### CODE REVIEW

**Comment by paulmelnikow** [comment]
Yea! Are these always set? Do they need to be added to the types?

**Comment by yomotsu** [comment]
> Yea! Are these always set?

Since it's just a getter, you can get the value whenever👍

> Do they need to be added to the types?

Do you mean d.ts? the d.ts is generated automatically.

**Comment by paulmelnikow** [comment]
Gotcha. Yea, this looks great!

**Comment by yomotsu** [comment]
Thanks for reviewing.
I will publish the next update this weekend, but if you need this asap, let me know.

**Comment by paulmelnikow** [comment]
I'm grabbing `_spherical` for the moment though I'd be happy to update it once this is merged.

**Pull request merged**
