### PR TITLE
Apply polar angle constraints in the setTarget method

### PR DESCRIPTION
**Pull request by virgilbugnariu**
Fixes https://github.com/yomotsu/camera-controls/issues/335

### CODE REVIEW

**Comment by yomotsu** [comment]
@virgilbugnariu 

Thanks for your first contribution!
It seems your commit removing necessary spaces in comments.
(2 spaces are for line breaks in markdown syntax)

Would you mind checking the diff, please?

**Comment by virgilbugnariu** [comment]
Yes, looks like my IDE did that automatically, I was not sure if that would be a problem. I will revert the changes on these lines and I'll update the PR. Thanks :)

**Comment by yomotsu** [comment]
Just merged!
Many thanks!

**Comment by VegarRingdalAibel** [comment]
think this broke using setPosition and setTarget 
if I stay before this release it all just works

I do something like this in my code on stored "viewpoints"

Maybe Im using it wrong..

```ts
const controllerPromise1 = getCanvasController()
      .getActiveControls()
      .setPosition(
          vp.controllerPosition[0],
          vp.controllerPosition[1],
          vp.controllerPosition[2],
          true
      );

  const controllerPromise2 = getCanvasController()
      .getActiveControls()
      .setTarget(
          vp.controllerTarget[0],
          vp.controllerTarget[1],
          vp.controllerTarget[2],
          true
      );
            ```

**Comment by yomotsu** [comment]
@VegarRingdalAibel

Would you mind opening a new issue with a working example, please?
This has been closed.

**Comment by VegarRingdalAibel** [comment]
Sure, Ill try and create something.
Just wanted to ask here incase I was using it wrong.

**Comment by VegarRingdalAibel** [comment]
Created it here: https://github.com/yomotsu/camera-controls/issues/345

**Pull request merged**
