### PR TITLE
add trackpad config

### PR DESCRIPTION
**Pull request by yomotsu**
see https://github.com/yomotsu/camera-controls/pull/66#issuecomment-572880522

### CODE REVIEW

**Comment by yomotsu** [comment]
@andrewplummer Could I make trackpad feature as experimental? I mean, when you use the feature, you need to enable the trackpad config.

```
cameraControls.enableUnstableTrackpadConfig = true;
cameraControls.trackpad.two = ACTION.TRUCK;
```

Because in order to detect trackpad move, it relies on `wheelDeltaY`, which is [a deprecated value](https://developer.mozilla.org/en-US/docs/Web/API/MouseWheelEvent) of MouseEvent.

**Comment by andrewplummer** [comment]
Yes absolutely! Feels like an experimental feature to me.

**Comment by yomotsu** [comment]
Thanks for understanding!
It's gonna be available as part of the lib at the next release.

**Comment by andrewplummer** [comment]
Update: I'm finally able to confirm this using my mouse, and it seems my assumption (taken from this SO post here: https://stackoverflow.com/questions/10744645/detect-touchpad-vs-mouse-in-javascript) is incorrect... at least for my Logitech Master 2s `wheelDeltaY` is always 3x `deltaY` so it is detecting as a trackpad. I've looked at everything else I can think of on the wheel event, and it seems that nothing works, unfortunately.

I think this PR still adds value as it allows trucking via the wheel event (this could be useful for a mouse wheel that has X axis as well). For now I think I'm going to have to simply use a UI toggle for zoom vs truck to handle this instead.

**Comment by yomotsu** [comment]
@andrewplummer Thanks for your report. So could we just remove the trackpad feature? Since the code is kinda hacky, it might cause other problems as well 😢

**Comment by andrewplummer** [comment]
What if we remove the `isTrackpad` code and config, and instead simply do `mouseButtons.wheel = ACTION.TRUCK`?

**Comment by yomotsu** [comment]
@andrewplummer okay, I'm working on it at https://github.com/yomotsu/camera-controls/pull/77

**Comment by andrewplummer** [comment]
Awesome, thank you!

**Pull request merged**
