### PR TITLE
Implement event dispatcher

### PR DESCRIPTION
**Pull request by FMS-Cat**
See #18.

`CameraControls` now inherits [`EventDispatcher`](https://github.com/FMS-Cat/camera-controls/blob/537d6f5a3703efe8f7d128ea7e0156fa79b79f64/src/event-dispatcher.js)
(The source is completely same as https://github.com/mrdoob/three.js/blob/master/src/core/EventDispatcher.js)

We initially have these events:

- `controlstart`
  when `mousedown` or `touchstart` is occured

- `control`
  when `mousemove` or `touchmove` is occured

- `controlend`
  when `mouseup` or `touchend` is occured

- `update`
  When the camera is updated via controls or transition

### CODE REVIEW

**Comment by yomotsu** [comment]
Thanks for your PR again. I definitely agreed using mrdoob's EventDispatcher.
Seems not bad. I approved to merge this.

**Comment by FMS-Cat** [comment]
Thanks? I also want to see your opinion about these events, is it excessive to implement / is there any other events that would be cool to be there?

**Comment by yomotsu** [comment]
I think should start with the minimum requirements. If someone needs, then we would consider and add. Too many features may cause confusion.

**Comment by FMS-Cat** [comment]
Okay!
I'm gonna update the README and merge it

**Pull request merged**
