### PR TITLE
Feature: rotateTo on one angle only

### PR DESCRIPTION
**Pull request by yannbriancon**
ref: https://github.com/yomotsu/camera-controls/issues/185

Add the possibility to rotate to an azimuth angle without changing the polar angle target (and vice versa)

- Allow use of undefined for rotateTo azimuthAngle and polarAngle parameters to keep the current value in sphericalEnd.theta or  sphericalEnd.phi

### CODE REVIEW

**Comment by yomotsu** [comment]
Thank you for your PR.
I personally think... I would like the argument to be required if it is not optional.
Could we have separated methods, which might be called `rotateAzimuthTo( azimuthAngleTo, enableTransition )` or so?

**Comment by yannbriancon** [comment]
Yes definitely!
I will update my PR later ;)

**Comment by yannbriancon** [comment]
@yomotsu I updated the PR with the new methods!

**Comment by yomotsu** [comment]
Thanks! LGTM!

**Comment by yomotsu** [comment]
Just merged.
This PR has been marked as next released and will be published on NPM this weekend.

**Pull request merged**
