### PR TITLE
Create use-with-react-three

### PR DESCRIPTION
**Pull request by moshuying**
I don't know how to convert the `@react-three/drei'and `@react-three/fiber' module dependencies from NPM into the reference mode of `<script src="*"></script>', so it looks like this

### CODE REVIEW

**Comment by moshuying** [comment]
This PR is the result of the following code packaging. I don't know how to use the method of online introduction. If you think of a better method here, show your ability
```tsx
import React, {Ref, Suspense, useEffect, useRef} from 'react';
import ReactDOM from 'react-dom';
import * as THREE from 'three';
import {Html} from '@react-three/drei';
import {Canvas, ReactThreeFiber, useFrame, useThree} from '@react-three/fiber';
import CameraControls from 'camera-controls';

CameraControls.install({THREE: THREE});

type OrbitControlsProps = ReactThreeFiber.Overwrite<
  ReactThreeFiber.Object3DNode<CameraControls, typeof CameraControls
    >, {
  target?: ReactThreeFiber.Vector3
  camera?: THREE.PerspectiveCamera | THREE.OrthographicCamera
  domElement?: HTMLElement
  regress?: boolean
  enableDamping?: boolean
  enabled?: boolean
  makeDefault?: boolean
  onControl?: (e?: THREE.Event) => void
  onControlStart?: (e?: THREE.Event) => void
  onControlEnd?: (e?: THREE.Event) => void
}>
const CustomCameraControls = React.forwardRef<CameraControls, OrbitControlsProps>(
    ({
      makeDefault,
      camera,
      regress,
      domElement,
      enabled=true,
      enableDamping = true,
      onControl,
      onControlStart,
      onControlEnd,
      ...restProps
    }, ref) => {
      const invalidate = useThree(({invalidate}) => invalidate);
      const defaultCamera = useThree(({camera}) => camera);
      const gl = useThree(({gl}) => gl);
      const set = useThree(({set}) => set);
      const get = useThree(({get}) => get);
      const performance = useThree(({performance}) => performance);
      const explCamera = camera || defaultCamera;
      const explDomElement = domElement || gl.domElement;
      const controls = React.useMemo(() => new CameraControls(explCamera, explDomElement), [explCamera]);

      const timeClock = React.useMemo(()=>new THREE.Clock(), []);

      useFrame(() => {
        controls.update(timeClock.getDelta());
      } );

      React.useEffect(() => {
        const callback = (e: THREE.Event) => {
          invalidate();
          if (regress) performance.regress();
          if (onControl) onControl(e);
        };

        controls.addEventListener('control', callback);

        if (onControlStart) controls.addEventListener('controlstart', onControlStart);
        if (onControlEnd) controls.addEventListener('controlend', onControlEnd);

        return () => {
          controls.removeEventListener('control', callback);
          if (onControlStart) controls.removeEventListener('controlstart', onControlStart);
          if (onControlEnd) controls.removeEventListener('controlend', onControlEnd);
          controls.dispose();
        };
      }, [explDomElement, onControl, onControlStart, onControlEnd, regress, controls, invalidate]);

      React.useEffect(() => {
        if (makeDefault) {
          const old = get().controls;
          // @ts-ignore
          set({controls});
          return () => set({controls: old});
        }
      }, [makeDefault, controls]);

      return <primitive ref={ref} object={controls} enableDamping={enableDamping} {...restProps} />;
    },
);

const AnimateCamera = ()=>{
  const ref = useRef<CameraControls>();
  useEffect(()=>{
    setInterval(()=>{
      if (!ref.current) return;
      ref.current.rotateTo(
          THREE.MathUtils.randFloat( 0, 2 * Math.PI ),
          THREE.MathUtils.randFloat( 0, Math.PI ), true,
      );
    }, 1000);
  }, []);
  return <CustomCameraControls ref={ref as unknown as Ref<CameraControls> | undefined} />;
};

const App = ()=>{
  return (
    <Canvas dpr={window.devicePixelRatio}>
      <AnimateCamera />
      <ambientLight color={'#ffffff'} intensity={1} />
      <axesHelper args={[5]} />
      <Suspense fallback={<Html center><p style={{textShadow: '3px 7px black', color: 'white'}}>Loading……</p></Html>}>
        <mesh>
          <boxBufferGeometry args={[1, 1, 1]}/>
          <meshBasicMaterial color={'#f00'} />
        </mesh>
      </Suspense>
    </Canvas>
  );
};

const div = document.createElement('div');
div.style.height = '100vh';
if (!document.body) {
  document.body = document.createElement('body');
}

ReactDOM.render(<App/>, document.body.appendChild(div));
```

**Comment by yomotsu** [comment]
Thanks for your PR.
I tried making an example with codesandbox.io.
How about just linking to this?
https://codesandbox.io/s/react-three-fiber-camera-controls-4jjor

**Comment by moshuying** [comment]
> Thanks for your PR. I tried making an example with codesandbox.io. How about just linking to this? https://codesandbox.io/s/react-three-fiber-camera-controls-4jjor

ok~ @yomotsu [https://codesandbox.io/s/react-three-fiber-camera-controls-h22dk](https://codesandbox.io/s/react-three-fiber-camera-controls-h22dk)

**Comment by yomotsu** [comment]
@moshuying Thanks! Your code was helpful to make the example!
Looking forward to having another PR from you😊

**Pull request closed without merging**
