### PR TITLE
[WIP] zoom to cursor

### PR DESCRIPTION
**Pull request by yomotsu**
see https://github.com/yomotsu/camera-controls/issues/100

support zoom-to-cursor

### CODE REVIEW

**Comment by FMS-Cat** [comment]
👀

**Comment by PerryRylance** [comment]
Hi @yomotsu , thank you so much for this,

I've rebuilt this at my end and found this works great for perspective cameras, how would we get this to work for Orthographic cameras?

Is that something you could potentially accommodate in this pull request?

**Comment by yomotsu** [comment]
@PerryRylance Actually I'm struggling with this PR,
I guess even the zoom to cursor for perspective cameras does not work correctory and will reject the PR at this moment😢

Hopefully, someone could help..🙏

**Comment by ebeit303** [comment]
Hi @yomotsu , Good Job.!!! 
Mouse pointer zoom works perfect, 

1. I check your examples, while setting infinityDolly as true, you checking with min distance which is always 0, so zoom cannot be done infinitely.
2. While Mouse pointer zoom, the target need to changed as per mouse pointer(camera direction), so the rotation will be done with the newly target not with (0,0,0). It is must if you looking for doing mouse pointer zoom

Other thing are Good..!!!! 
Have a good Day.

**Comment by yomotsu** [comment]
sorry but let me drop this PR for now.
maybe try this again sometime soon.

**Pull request closed without merging**
