### PR TITLE
eslint should ignore dist and node_modules

### PR DESCRIPTION
**Pull request by FMS-Cat**
low priority qol

### CODE REVIEW

**Comment by yomotsu** [comment]
Thanks!
Would you mind adding this to package.json?
https://eslint.org/docs/user-guide/configuring#using-eslintignore-in-package-json

**Comment by FMS-Cat** [comment]
oh you are using package.json side eslint config, didn't notice that, my bad

**Comment by FMS-Cat** [comment]
✔️

**Comment by yomotsu** [comment]
many thanks!

**Pull request merged**
