### PR TITLE
added support for infinity dolly while using dolly to cursor

### PR DESCRIPTION
**Pull request by cotlod**
Fixes > [Issue 175](https://github.com/yomotsu/camera-controls/issues/175)

### CODE REVIEW

**Comment by yomotsu** [comment]
Thanks for your contribution.
However, It seems your PR contains unnecessary changes.

Could you focus only on the subject?
The PR suppose to only contain `src/CameraControls.ts`.

**Comment by cotlod** [comment]
should I move the eslint section into another PR, because this would  help greatly with autoformatting

**Comment by cotlod** [comment]
@yomotsu cleaned!

**Comment by yomotsu** [comment]
Thanks! merged!

**Pull request merged**
