### PR TITLE
feature: seprate domElement and other HTMLElement touch event

### PR DESCRIPTION
**Pull request by FateLocker**

### CODE REVIEW

**Comment by yomotsu** [comment]
Sorry for the long delay...
Could I hear about the usecase?

**Comment by FateLocker** [comment]
I am trying to add an analog joystick to the window, which can manipulate the position of the camera; but I hope that the camera-control will not recognize the touch event on the joystick view

**Comment by yomotsu** [comment]
That makes sense. I understand.
But this change could be a breaking change.

How about adding a new property called `ignoreElements[]` or so?

**Comment by FateLocker** [comment]
It could not be better

**Comment by yomotsu** [comment]
Thank you for understanding.
If you are still interested in the PR, I will happy to receive the change.
I can also work on it based on your PR but it may take some time.

**Comment by yomotsu** [comment]
@FateLocker 

Hey, I've added PointerEvent API support.
I think it's easy to ignore events that started from `ignoreElements`.

https://github.com/yomotsu/camera-controls/blob/ac39858d675fd30b831968c5642c9723a7debf8c/src/CameraControls.ts#L264-L278

If the event started from `ignoreElements`, the only we need is just `return` immediately!

**Comment by FateLocker** [comment]
It has only responded to `domElement`, but its normal function is affected by 'isPointerEventsNotSupported'

https://github.com/yomotsu/camera-controls/blob/ac39858d675fd30b831968c5642c9723a7debf8c/src/CameraControls.ts#L790-L791

**Comment by yomotsu** [comment]
That's right. So, we can just ignore the event at the beginning of the handlers.
`onPointerDown`
`onMouseDown`
`onTouchStart`

```js
const onMouseDown = ( event ) => {

  // if event.target is a descendant of ignoreElement, return here

}
```

And do the same for other handlers.

**Comment by FateLocker** [comment]
I mean that after using PointerEvents, other HTMLElement will no longer affect CameraControls.

**Comment by yomotsu** [comment]
Ah, I see!
So you mean, this PR is no longer needed?

**Comment by yomotsu** [comment]
@FateLocker
Thank you for your PR anyway!
I'm looking forward to another PR from you and joining as a contributor!

**Pull request closed without merging**
